image: node:latest

cache:
  paths:
  - node_modules/

pages:
  stage: deploy
  script:
  - export NODE_ENV=production
  - npm install
  - npm run build
  artifacts:
    paths:
    - build
  only:
  - master
